version = 0.1

[default.deploy.parameters]
stack_name = "mortgage-guardian-backend"
resolve_s3 = true
s3_prefix = "mortgage-guardian-backend"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "PlaidClientID=\"68bdabb75b00b300221d6a6f\""
image_repositories = []
